apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-ms-c
  name: admin-ms-c
spec:
  type: NodePort
  ports:
    - name: "9101"
      port: 9101
      targetPort: 9101
      nodePort: 30011
  selector:
    app: admin-ms-c

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-ms-c
  name: admin-ms-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-ms-c
  template:
    metadata:
      labels:
        app: admin-ms-c
    spec:
      containers:
        - image: usr998/atlant-devops:admin-ms
          name: admin-ms-c
          ports:
            - containerPort: 9101
          resources: {}
      restartPolicy: Always

