ms:
  names:
    admin: admin-ms-c
    biz: biz-ms-c
    news: news-ms-c
    website: website-ms-c
  
  images:
    admin: usr998/atlant-devops:admin-ms
    biz: usr998/atlant-devops:biz-ms
    news: usr998/atlant-devops:news-ms
    website: usr998/atlant-devops:website-ms-kube
  
  ports:
    admin: 9101
    biz: 9001
    news: 9201
    website: 9301
  
  targetPorts:
    admin: 9101
    biz: 9001
    news: 9201
    website: 9301
  
  nodePorts:
    admin: 30011
    news: 30021
    website: 30031

  replicas:
    admin: 1
    biz: 1
    news: 1
    website: 1

  serviceTypes:
    admin: NodePort
    news: NodePort
    website: NodePort

database:
  name: psql-ms
  image: postgres:10
  port: 5432
  targetPort: 5432
  replicas: 1

  env:
    pgUser: demo
    pgPassword: demo

