apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.db.name }}
  name: {{ .Values.db.name }}
spec:
  ports:
    - name: "5432"
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.targetPort }}
  selector:
    app: {{ .Values.db.name }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.db.name }}
  name: {{ .Values.db.name }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.env.pgPassword }}
            - name: POSTGRES_USER
              value: {{ .Values.db.env.pgUser }}
          image: {{ .Values.db.image }}
          name: {{ .Values.db.name }}
          ports:
            - containerPort: {{ .Values.db.port }}
          resources: {}
      restartPolicy: Always

